{% set name = "email-validator" %}
{% set version = "1.1.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/JoshData/python-email-validator/archive/v{{ version }}.tar.gz
  sha256: d72cede858e5bdde6f8cce85a75d671e1748278729c92b802e8e6e1cd852b710

build:
  number: 0
  noarch: python
  entry_points:
    - email_validator=email_validator:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - dnspython >=1.15.0
    - idna >=2.0.0
    - pip
    - python
    - setuptools
    - wheel
  run:
    - dnspython >=1.15.0
    - idna >=2.0.0
    - python

test:
  source_files:
    - tests
  requires:
    - coverage
    - docutils
    - flake8
    - pytest
    - pytest-cov
    - pip
  imports:
    - email_validator
  commands:
    - pip check
    - email_validator --help
    - pytest --cov=email_validator

about:
  home: https://github.com/JoshData/python-email-validator
  license: CC0-1.0
  license_family: CC
  license_file: LICENSE
  summary: A robust email syntax and deliverability validation library for Python 2.x/3.x.
  doc_url: https://github.com/JoshData/python-email-validator
  dev_url: https://github.com/JoshData/python-email-validator

extra:
  recipe-maintainers:
    - xylar
